<h1>Data Preprocessing Tools</h1>

In [2]:
#Importing the Libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
#Import Dataset

In [5]:
dataset = pd.read_csv('Data.csv')

In [9]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [11]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [13]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [15]:
#Taking care of missing data

In [17]:
from sklearn.impute import SimpleImputer

In [19]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [21]:
imputer.fit(x[:,1:3])

SimpleImputer()

In [23]:
x[:,1:3] = imputer.transform(x[:,1:3])

In [25]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [27]:
#Encoding Categorical data

In [29]:
#Encoding the Independent Variable

In [33]:
from sklearn.compose import ColumnTransformer

In [35]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [39]:
x = np.array(ct.fit_transform(x))

In [41]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [43]:
#Encoding the Dependent Varible

In [45]:
from sklearn.preprocessing import LabelEncoder

In [47]:
le = LabelEncoder()

In [49]:
y = le.fit_transform(y)

In [51]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [53]:
#Splitting the dataset into the Traning Set and Test set

In [55]:
from sklearn.model_selection import train_test_split

In [57]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [59]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [61]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [63]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [65]:
print(y_test)

[0 1]


In [67]:
#Feature Scaling

In [69]:
from sklearn.preprocessing import StandardScaler

In [71]:
sc = StandardScaler()

In [73]:
X_train[:,3:] = sc.fit_transform(X_train[:,3:])

In [75]:
X_test[:,3:] = sc.transform(X_test[:,3:])